//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionDetail
    {
        public int ExecutionDetailID { get; set; }
        public Nullable<int> ExecutionSummaryId { get; set; }
        public Nullable<System.DateTime> ExecutionDetailStartDate { get; set; }
        public Nullable<System.DateTime> ExecutionDetailEndDate { get; set; }
        public string ExecutionDetailLookupTable { get; set; }
        public string ExecutionDetailStatus { get; set; }
        public string ExecutionErrorDescription { get; set; }
        public Nullable<byte> ExecutionDetailLookupRecordCount { get; set; }
    }
}
