//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionSummary
    {
        public int ExecutionSummaryId { get; set; }
        public Nullable<System.DateTime> ExecutionSummaryStartDate { get; set; }
        public Nullable<System.DateTime> ExecutionSummaryEndDate { get; set; }
        public string BenchmarkYear { get; set; }
        public Nullable<short> TargetBenchmarkCount { get; set; }
        public Nullable<short> PopulatedBenchmarkCount { get; set; }
        public string ExecutionSummaryStatus { get; set; }
        public string ExecutionBenchmarkType { get; set; }
    }
}
