//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookup_averageframesmarkup_j
    {
        public byte rowid { get; set; }
        public Nullable<decimal> lookupvalue { get; set; }
        public Nullable<decimal> responsemin { get; set; }
        public Nullable<decimal> responsemax { get; set; }
        public Nullable<decimal> percentile { get; set; }
        public string lookuplable { get; set; }
    }
}
