//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup_ExamFeeSoftNewFitTORIC
    {
        public int RowId { get; set; }
        public Nullable<decimal> LookupValue_ { get; set; }
        public Nullable<decimal> ResponseMin_ { get; set; }
        public Nullable<decimal> ResponseMax_ { get; set; }
        public Nullable<decimal> Percentile { get; set; }
        public string LookupLable { get; set; }
    }
}
