//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public Rule()
        {
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
        }
    
        public int RuleId { get; set; }
        public string RuleName { get; set; }
        public string Description { get; set; }
        public bool IsNumeric { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> QuestionRef { get; set; }
        public Nullable<bool> IsEqual { get; set; }
        public Nullable<bool> IsGreaterThan { get; set; }
        public Nullable<bool> IsLessThan { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
    }
}
