//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionMaster
    {
        public SectionMaster()
        {
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
        }
    
        public int SectionId { get; set; }
        public string Section { get; set; }
        public byte OrderNo { get; set; }
        public byte YearId { get; set; }
        public byte SurveyId { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
    }
}
