//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubQuestion
    {
        public int Id { get; set; }
        public string SubQuestionText { get; set; }
        public string SubDtype { get; set; }
        public string ControlRendered { get; set; }
        public int QuestionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SubAdditionalText { get; set; }
        public Nullable<int> SubOrder { get; set; }
        public Nullable<int> QuestionOrderNo { get; set; }
    
        public virtual SurveyQuestion SurveyQuestion { get; set; }
    }
}
