//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestion
    {
        public SurveyQuestion()
        {
            this.SubQuestions = new HashSet<SubQuestion>();
        }
    
        public int QuestionId { get; set; }
        public string QuestionText { get; set; }
        public string QuestionDataType { get; set; }
        public string ControlRendered { get; set; }
        public int OrderNo { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> RuleId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> HavingSubQuestion { get; set; }
        public string DbColumnName { get; set; }
        public Nullable<bool> ShowTotal { get; set; }
        public string AdditionalText { get; set; }
        public string HelpText { get; set; }
    
        public virtual Rule Rule { get; set; }
        public virtual SectionMaster SectionMaster { get; set; }
        public virtual ICollection<SubQuestion> SubQuestions { get; set; }
    }
}
