//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticePerformanceAssessmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyTbl
    {
        public SurveyTbl()
        {
            this.Practices = new HashSet<Practice>();
        }
    
        public int Id { get; set; }
        public string SurveyText { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Practice> Practices { get; set; }
    }
}
